### ISSUE TITLE
Needs genanki >=0.12.0

### ISSUE THREAD

**Issue by tbm** [abdnh/50langs2anki#1]
I got the following errors:

```
python3 fiftylangs2anki.py --src en --dest af                                                          master
Generating 50Languages_en-af_1-100.apkg...
Fetching lesson 1...Traceback (most recent call last):
  File "/home/tbm/tmp/scratch/afrikaans/x/50langs2anki/fiftylangs2anki.py", line 289, in <module>
    generate_deck(args.src, args.dest, args.start, args.end, args.model_id, args.out)
  File "/home/tbm/tmp/scratch/afrikaans/x/50langs2anki/fiftylangs2anki.py", line 219, in generate_deck
    add_note(
  File "/home/tbm/tmp/scratch/afrikaans/x/50langs2anki/fiftylangs2anki.py", line 138, in add_note
    note = genanki.Note(
TypeError: __init__() got an unexpected keyword argument 'due'
```

I had genanki-0.10.1.  `due` was added in 0.12.0, see https://github.com/kerrickstaley/genanki/commit/6ceffc1b707ad67efa2adf4534d143a142487df8

Can you update requirements.txt to say `>=0.12.0`

Thanks for writing this script. I was just going to do something similar when I found your solution!

**Comment by abdnh** [comment]
Done. Thanks!
